import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { headers } from "next/headers";
import { Viewport } from "@/types/common";
import React from "react";
import CartDialog from "@/components/dialogs/cartDialog";
import AccountDialog from "@/components/dialogs/accountDialog/accountDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = headers();
  const viewport = header.get("viewport");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header viewport={viewport as Viewport} />
        {children}
        <CartDialog />
        <AccountDialog />
      </body>
    </html>
  );
}
